"""End-user interaction acceptance, invoked by the existing real-GUI CI suite.
Uses only the already crawled local visual fixture; presentation preferences never
persist URLs or selections. Screenshots show actual implemented controls.
"""
import csv
import io
import json
from pathlib import Path
from playwright.sync_api import expect


def run_interaction_checks(page, docs: Path):
    page.set_viewport_size({'width': 1440, 'height': 1000})
    page.get_by_role('button', name='Home', exact=True).click()
    expect(page.get_by_role('heading', name='Inspect a website.', exact=True)).to_be_visible()
    expect(page.locator('.home-recent')).to_have_count(2)
    page.screenshot(path=str(docs/'interaction-home.png'), full_page=True)
    # URL-first entry configures a crawl but never submits a job without review.
    history_count = page.locator('#history-count').inner_text().strip()
    page.locator('#quick-url').fill('example.com/docs#intro')
    page.get_by_role('button', name='Configure crawl', exact=True).click()
    expect(page.get_by_role('dialog', name='Where should we start?', exact=True)).to_be_visible()
    expect(page.locator('#url-input')).to_have_value('https://example.com/docs')
    expect(page.locator('#crawl-plan')).to_contain_text('50 candidate URLs')
    page.locator('[name=preset][value="200"]').check()
    expect(page.locator('#crawl-plan')).to_contain_text('200 candidate URLs')
    page.locator('[name=mode][value=http]').check()
    expect(page.locator('#crawl-plan')).to_contain_text('No browser')
    assert history_count == page.locator('#history-count').inner_text().strip()
    page.screenshot(path=str(docs/'interaction-setup.png'), full_page=True)
    page.get_by_role('button', name='Close new crawl', exact=True).click()
    expect(page.get_by_role('button', name='Configure crawl', exact=True)).to_be_focused()
    page.locator('#quick-url').fill('javascript:alert(1)')
    page.get_by_role('button', name='Configure crawl', exact=True).click()
    expect(page.locator('#quick-error')).to_be_visible()
    page.locator('#quick-url').fill('')
    page.locator('.home-recent').first.click()
    expect(page.locator('#metric-pages')).to_have_text('37')
    page.get_by_role('tab', name='Pages', exact=True).click()
    expect(page.locator('#run-diagnostics')).not_to_have_attribute('open', '')
    expect(page.locator('.page-grid tbody tr')).to_have_count(20)
    # Selecting a row must not snap a long inventory back to its first row.
    page.locator('.page-grid-scroll').evaluate('(el)=>el.scrollTop=300')
    page.locator('[data-select-url]').nth(8).check()
    assert page.locator('.page-grid-scroll').evaluate('(el)=>el.scrollTop') >= 250
    expect(page.locator('[data-select-url]').nth(8)).to_be_focused()
    page.locator('[data-action=clear-selection]').click()
    page.locator('.page-grid-scroll').evaluate('(el)=>el.scrollTop=0')
    # Semantic sorting works in both directions without mutating source records.
    page.locator('[data-page-sort=words]').click()
    expect(page.locator('th[aria-sort]')).to_have_attribute('aria-sort','descending')
    page.locator('[data-page-sort=words]').click()
    expect(page.locator('th[aria-sort]')).to_have_attribute('aria-sort','ascending')
    page.locator('#sort').select_option('url')
    rows = page.locator('[data-select-url]')
    chosen = [rows.nth(i).get_attribute('data-select-url') for i in range(2)]
    rows.nth(0).check()
    expect(page.locator('[data-select-url]').nth(0)).to_be_focused()
    rows.nth(1).check()
    expect(page.locator('#selection-count')).to_have_text('2 selected')
    assert page.locator('#select-visible').evaluate('(el)=>el.indeterminate')
    page.locator('#search').fill('/journal')
    expect(page.locator('#selection-hidden')).to_have_text('2 outside current filters')
    with page.expect_download() as item:
        page.locator('#pages-export').click()
    contents = list(csv.DictReader(io.StringIO(Path(item.value.path()).read_text())))
    assert item.value.suggested_filename == 'selected-pages.csv'
    assert len(contents) == 2 and {row['URL'] for row in contents} == set(chosen)
    page.locator('[data-action=clear-selection]').click()
    expect(page.locator('#page-selection')).to_be_hidden()
    with page.expect_download() as item:
        page.locator('#pages-export').click()
    contents = list(csv.DictReader(io.StringIO(Path(item.value.path()).read_text())))
    assert len(contents) == 6 and all('/journal' in row['URL'] for row in contents)
    page.locator('#search').fill('no-such-captured-page')
    expect(page.get_by_role('heading',name='No matching pages',exact=True)).to_be_visible()
    expect(page.locator('#pages-export')).to_be_disabled()
    page.locator('#clear-filters').click()
    page.locator('#page-size').select_option('50')
    expect(page.locator('.page-grid tbody tr')).to_have_count(37)
    page.locator('#select-visible').check()
    expect(page.locator('#selection-count')).to_have_text('37 selected')
    page.locator('[data-action=clear-selection]').click()
    page.locator('#page-size').select_option('20')
    page.locator('#table-footer [data-action=next]').click()
    expect(page.locator('.page-grid tbody tr')).to_have_count(17)
    page.locator('#select-visible').check()
    expect(page.locator('#selection-count')).to_have_text('17 selected')
    page.locator('#table-footer [data-action=previous]').click()
    expect(page.locator('[data-select-url]:checked')).to_have_count(0)
    page.locator('[data-action=clear-selection]').click()
    # Column settings are optional presentation preferences; user data is not stored.
    page.locator('#page-columns summary').click()
    page.locator('[data-page-column=external]').uncheck()
    expect(page.locator('[data-page-sort=external]')).to_have_count(0)
    page.locator('[data-page-column=external]').press('Escape')
    expect(page.locator('#page-columns summary')).to_be_focused()
    page.reload(wait_until='networkidle')
    expect(page.locator('#metric-pages')).to_have_text('37')
    expect(page.locator('[data-page-sort=external]')).to_have_count(0)
    page.locator('#page-columns summary').click()
    page.locator('[data-page-column=external]').check()
    page.locator('[data-page-column=external]').press('Escape')
    page.locator('#search').fill('/journal')
    ordered = page.locator('.page-link').evaluate_all('(els)=>els.map(e=>e.dataset.page)')
    page.locator('.page-link').first.click()
    expect(page.locator('#inspect-position')).to_have_text('1 of 6 pages')
    expect(page.locator('#inspect-previous')).to_be_disabled()
    page.locator('#inspect-tab-content').click()
    page.locator('#inspect-next').click()
    expect(page.locator('#inspect-position')).to_have_text('2 of 6 pages')
    expect(page.locator('#inspect-tab-content')).to_have_attribute('aria-selected','true')
    assert ordered[1] in page.locator('.inspect-identity').inner_text()
    page.keyboard.press('Alt+ArrowRight')
    expect(page.locator('#inspect-position')).to_have_text('3 of 6 pages')
    page.screenshot(path=str(docs/'interaction-inspector.png'), full_page=True)
    page.get_by_role('button', name='Close page details', exact=True).click()
    expect(page.locator('.page-link').first).to_be_focused()
    page.locator('#clear-filters').click()
    # Metric buttons lead to useful, filtered workspaces rather than dead summary cards.
    page.get_by_role('button',name='Browse images',exact=True).click()
    expect(page.locator('.atlas-elements')).to_be_visible()
    page.get_by_role('button',name='Explore external links',exact=True).click()
    expect(page.locator('#tab-links')).to_have_attribute('aria-selected','true')
    page.get_by_role('button',name='View crawled pages',exact=True).click()
    page.keyboard.press('Control+k')
    page.locator('#command-search').fill('resources')
    page.locator('#command-search').press('ArrowDown')
    expect(page.locator('[data-jump=resources]')).to_be_focused()
    page.keyboard.press('Enter')
    expect(page.locator('#tab-resources')).to_have_attribute('aria-selected','true')
    page.get_by_role('button',name='Crawl history',exact=True).click()
    page.locator('#history-search').fill('no-such-crawl')
    expect(page.locator('.history-card')).to_have_count(0)
    page.get_by_role('button',name='Reset history filters',exact=True).click()
    expect(page.locator('.history-card')).to_have_count(2)
    page.locator('#history-search').fill('visual atlas')
    expect(page.locator('.history-card')).to_have_count(1)
    page.get_by_role('button',name='Open',exact=True).click()
    page.get_by_role('button',name='Collapse sidebar',exact=True).click()
    expect(page.locator('html')).to_have_attribute('data-sidebar','collapsed')
    # Collapsed controls still have useful accessible names.
    expect(page.get_by_role('button',name='Owner access',exact=True)).to_be_visible()
    page.reload(wait_until='networkidle')
    expect(page.locator('html')).to_have_attribute('data-sidebar','collapsed')
    page.get_by_role('button',name='Expand sidebar',exact=True).click()
    page.get_by_role('tab',name='Pages',exact=True).click()
    expect(page.locator('#metric-pages')).to_have_text('37')
    page.screenshot(path=str(docs/'interaction-pages.png'), full_page=True)
    for width in [1440, 1100, 900, 390]:
        page.set_viewport_size({'width':width,'height':1000})
        expect(page.locator('.result-tabs[role=tablist]')).to_have_count(1)
        expect(page.locator('#tab-pages')).to_be_visible()
        assert page.evaluate('document.documentElement.scrollWidth <= innerWidth+1'), width
        expect(page.locator('.page-grid-scroll')).to_be_visible()
        # All configured headers remain in the table on small screens, not hidden.
        expect(page.locator('[data-page-sort=words]')).to_be_visible()
        if width == 390: page.screenshot(path=str(docs/'interaction-mobile.png'),full_page=True)
    page.set_viewport_size({'width':1440,'height':1000})
    page.get_by_role('button',name='Workspace settings',exact=True).click()
    expect(page.get_by_role('dialog',name='Workspace settings',exact=True)).to_be_visible()
    page.locator('#settings-dialog [data-action=density]').click()
    expect(page.locator('html')).to_have_attribute('data-density','compact')
    page.locator('#settings-dialog [data-action=glass]').click()
    expect(page.locator('html')).to_have_attribute('data-transparency','reduce')
    page.get_by_role('button',name='Close workspace settings',exact=True).click()
    page.locator('#theme-toggle').click()
    page.screenshot(path=str(docs/'interaction-dark.png'),full_page=True)
    # Selection and URLs are not presentation preferences and must not leak into them.
    saved = page.evaluate('JSON.stringify({...localStorage})')
    assert all(url not in saved for url in chosen)
    page.locator('#theme-toggle').click()
    print(json.dumps({'interaction':'PASS','checks':['URL review before network','crawl plan','native sorting','selection across pages and filters','scoped CSV rows','column persistence','empty recovery','inspector sequence and keyboard','metric navigation','keyboard commands','searchable history','collapsed rail names','responsive tables','appearance preferences']},indent=2))
