/** Deterministic presentation-model tests; no external websites or UI framework required. */
import test from 'node:test';
import assert from 'node:assert/strict';
// UI output is built before this suite; these modules have no browser-only side effects.
import { PageSelection, sortPages, visibleColumns, pageGrid, pageColumns } from '../ui-dist/page-grid.js';
import { normalizeWebsite, describePlan } from '../ui-dist/interaction.js';
const page = (id, words) => ({ url:`https://fixture.example/${id}`, title:id, heading:'', status_code:200, depth:1, internal_links:[], external_links:[], duration_ms:20, inspection: words === undefined ? undefined : {word_count:words} });
test('Page selection is cleared for a different crawl and pruned for removed records', () => { const s=new PageSelection(); const a=page('a',1), b=page('b',2); s.use('1',[a,b]);s.setPage([a,b],true);s.use('1',[a]);assert.deepEqual([...s.urls],[a.url]);s.use('2',[a]);assert.equal(s.urls.size,0); });
test('Explicit selection takes precedence over filters without losing hidden selections', () => { const s=new PageSelection(); const a=page('a',1), b=page('b',2);s.use('1',[a,b]);s.toggle(a.url,true);assert.deepEqual(s.exportRows([a,b],[b]),[a]);s.clear();assert.deepEqual(s.exportRows([a,b],[b]),[b]); });
test('Select visible affects only the page supplied and unknown measurements sort last both ways', () => { const s=new PageSelection();const a=page('a',2), b=page('b',5), c=page('c');s.setPage([a,b],true);s.setPage([b],false);assert.deepEqual([...s.urls],[a.url]);assert.deepEqual(sortPages([c,b,a],'words').map(p=>p.title),['a','b','c']);assert.deepEqual(sortPages([c,b,a],'words',true).map(p=>p.title),['b','a','c']); });
test('Sorting is stable and leaves the supplied records untouched', () => { const input=[page('z',2),page('a',2)];assert.deepEqual(sortPages(input,'words').map(p=>p.title),['a','z']);assert.equal(input[0].title,'z'); });
test('Visible columns are bounded and allowlisted', () => { assert.deepEqual(visibleColumns(['words','words','script','status']),['status','words']);assert.deepEqual(visibleColumns(null),[...pageColumns]);assert.deepEqual(visibleColumns([]),[]); });
test('Inventory escapes untrusted page title and declares its sorted header', () => {const p=page('safe',1);p.title='<img src=x onerror=alert(1)>';const html=pageGrid({pages:[p],selected:new Set(),columns:['words'],sort:'words',descending:true,review:new Set()});assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('<img'));assert.ok(html.includes('aria-sort="descending"'));assert.ok(html.includes('scope="col"'));});
test('Website entry accepts omitted scheme, removes fragments and rejects embedded credentials', () => {assert.equal(normalizeWebsite(' example.com/path#one '),'https://example.com/path');for(const url of ['', 'javascript:alert(1)', 'https://user:secret@example.com'])assert.throws(()=>normalizeWebsite(url));});
test('Plan summary describes budgets rather than promising whole-site completion', () => {assert.match(describePlan('smart',50,10),/candidate URLs/);assert.match(describePlan('http',50,10),/No browser/);assert.match(describePlan('browser',NaN,NaN),/— candidate/);});
