/** Real inert jsdom extraction; no remote websites or script execution. */
import test from 'node:test';
import assert from 'node:assert/strict';
import { extractPageDetails } from '../dist/extract.js';
const inspect = html => extractPageDetails(html, 'https://fixture.example').inspection;
test('static audit recognizes document language, H1 and missing alt without penalizing decorative alt', () => {const a=inspect('<html lang="en"><h1>Hello</h1><img src="x" alt=""><img src="y"><h1 hidden>Ignore</h1></html>').accessibility; assert.equal(a.language,'en');assert.equal(a.h1_count,1);assert.equal(a.images,2);assert.equal(a.images_missing_alt,1);});
test('explicit, wrapping and aria names are recognized but placeholder is not a label', () => {const a=inspect('<label for="one">Name</label><input id="one"><label>Address<input></label><input aria-label="City"><input placeholder="not a name"><input type="hidden"><textarea aria-labelledby="label"></textarea><span id="label" hidden>Message</span>').accessibility;assert.equal(a.controls,5);assert.equal(a.controls_without_name,1);});
test('links recognize image alt but ignore hidden descendants', () => {const a=inspect('<a href="/a"><img alt="Home" src="x"></a><a href="/b"><span hidden>Hidden</span></a><a href="/c" aria-hidden="true"></a><a href="/d" aria-label="Visit"></a>').accessibility;assert.equal(a.links,3);assert.equal(a.links_without_name,1);});
test('native input buttons, SVG title and explicit names are recognized', () => {const a=inspect('<input type="submit"><input type="reset"><input type="button" value="Go"><input type="image" alt="Search"><button><svg><title>Menu</title></svg></button><button></button>').accessibility;assert.equal(a.buttons,6);assert.equal(a.buttons_without_name,1);});
test('a capped snapshot reports truncation and inspected element budget', () => {const a=inspect('<div>'+ '<span>x</span>'.repeat(5100) +'</div><h1>Beyond budget</h1>').accessibility;assert.equal(a.truncated,true);assert.equal(a.inspected_elements,5000);assert.equal(a.h1_count,0);});
test('fingerprints use full normalized body text, ignore scripts and differ beyond text sample', () => {const a=inspect('<body><p>Same  text</p><script>malicious()</script></body>');const b=inspect('<body><div>Same text</div></body>');assert.equal(a.content_fingerprint,b.content_fingerprint);const prefix='a'.repeat(4100);assert.notEqual(inspect(`<body>${prefix}X</body>`).content_fingerprint,inspect(`<body>${prefix}Y</body>`).content_fingerprint);});
test('empty and truncated body text do not receive misleading fingerprints', () => {assert.equal(inspect('<body><script>not visible</script></body>').content_fingerprint,undefined);assert.equal(inspect('<body>'+'a'.repeat(2*1024*1024)+'</body>').content_fingerprint,undefined);});
test('inert static checks do not execute scripts and never collect input values', () => {const data=inspect('<input value="PRIVATE-SAMPLE" placeholder="Name"><script>globalThis.__auditExecuted=true</script>');assert.equal(globalThis.__auditExecuted,undefined);assert.ok(!JSON.stringify(data.accessibility).includes('PRIVATE-SAMPLE'));});
