/** Evidence aggregation stays deterministic and independent of browser/network state. */
import test from 'node:test';
import assert from 'node:assert/strict';
import { analyzeCrawl, filterFindings, percentile, rankPages } from '../ui-dist/observatory-model.js';
import { accessPreferences } from '../ui-dist/accessibility.js';
import { csv } from '../ui-dist/atlas-shared.js';
const page = (id, changes = {}) => ({ url: `https://fixture.example/${id}`, requested_url: `https://fixture.example/${id}`, heading: 'Heading', first_paragraph: '', outgoing_links: [], image_urls: [], title: id, description: 'A description', status_code: 200, depth: 1, duration_ms: 100, content_bytes: 100, internal_links: [], external_links: [], ...changes });
const result = (pages, errors = []) => ({ pages: Object.fromEntries(pages.map(p => [p.url, p])), errors });
const snapshot = (changes = {}) => ({ version: 1, language: 'en', h1_count: 1, images: 2, images_missing_alt: 0, controls: 1, controls_without_name: 0, links: 1, links_without_name: 0, buttons: 1, buttons_without_name: 0, inspected_elements: 20, truncated: false, ...changes });
test('empty capture has unknown coverage and timing, not fabricated success', () => { const m = analyzeCrawl(); assert.equal(m.pages, 0); assert.equal(m.median, null); assert.equal(m.p95, null); assert.ok(m.coverage.every(c => c.percent === null)); assert.ok(m.outcomes.every(b => b.count === 0)); });
test('legacy histories do not invent accessibility measurements', () => { const m = analyzeCrawl(result([page('old')])); assert.equal(m.inspected, 0); assert.deepEqual(m.coverage.map(c => c.percent), [100, 100, null, null, null, null]); });
test('coverage uses actual denominators including decorative alt and named controls', () => { const m = analyzeCrawl(result([page('a', { inspection: { accessibility: snapshot({ images_missing_alt: 1, controls_without_name: 1 }) } })])); assert.deepEqual(m.coverage.map(c => c.percent), [100,100,100,100,50,0]); assert.equal(m.findings.filter(f => f.category === 'Accessibility').length, 2); });
test('partial samples are disclosed and excluded from element coverage', () => { const m = analyzeCrawl(result([page('a', { inspection: { accessibility: snapshot({ truncated: true, h1_count: 0 }) } })])); assert.equal(m.partial, 1); assert.deepEqual(m.coverage.map(c => c.percent), [100,100,null,100,null,null]); assert.equal(m.findings.some(f => f.title === 'No main heading'), false); assert.ok(m.findings.some(f => f.title === 'Accessibility sample capped')); });
test('no eligible images or controls is N/A, not 100 percent', () => { const m = analyzeCrawl(result([page('a', { inspection: { accessibility: snapshot({ images: 0, controls: 0 }) } })])); assert.equal(m.coverage[4].percent, null); assert.equal(m.coverage[5].percent, null); });
test('duplicate body text requires complete versioned SHA-256 fingerprints', () => { const hash = 'sha256-text-v1:' + 'a'.repeat(64); const m = analyzeCrawl(result([page('a', { inspection: { content_fingerprint: hash } }), page('b', { inspection: { content_fingerprint: hash } }), page('c', { inspection: { content_fingerprint: 'short' } })])); assert.equal(m.duplicateGroups, 1); assert.equal(m.fingerprinted, 2); assert.equal(m.findings.filter(f => f.title === 'Matching body text').length, 2); assert.equal(m.findings[0].related_url, 'https://fixture.example/b'); });
test('repeated titles are case-sensitive, trimmed and ignore empty titles', () => { const m = analyzeCrawl(result([page('a', { title: 'Same' }), page('b', { title: ' Same ' }), page('c', { title: 'same' }), page('d', { title: '' })])); assert.equal(m.findings.filter(f => f.title === 'Repeated title').length, 2); });
test('failed internal destination evidence excludes unvisited and robots-only failures', () => { const p = page('a', { internal_links: ['https://fixture.example/missing#one', 'https://fixture.example/missing#two', 'https://fixture.example/unvisited', 'https://fixture.example/blocked'] }); const m = analyzeCrawl(result([p], [{ url: 'https://fixture.example/missing', status_code: 404, stage: 'page' }, { url: 'https://fixture.example/blocked', status_code: 403, stage: 'robots' }])); const f = m.findings.find(f => f.category === 'Links'); assert.match(f.detail, /1 distinct/); assert.match(f.detail, /HTTP 404/); assert.doesNotMatch(f.detail, /HTTP 403/); assert.equal(m.outcomes.find(b => b.label === '4xx').count, 1); });
test('eventual captured success supersedes a prior error for requested URL', () => { const p = page('final', { requested_url: 'https://fixture.example/old' }); const source = page('source', { internal_links: ['https://fixture.example/old'] }); const m = analyzeCrawl(result([p, source], [{ url: 'https://fixture.example/old', status_code: 503 }])); assert.equal(m.findings.filter(f => f.category === 'Links').length, 0); assert.equal(m.outcomes.find(b => b.label === '5xx').count, 0); });
test('incoming count deduplicates repeated links on a source page', () => { const m = analyzeCrawl(result([page('a'), page('b', { internal_links: ['https://fixture.example/a', 'https://fixture.example/a#x'] })])); assert.equal(m.metrics.find(p => p.title === 'a').incoming, 1); });
test('timing bins have explicit boundaries and invalid values remain unknown', () => { const values = [0,249,250,999,1000,2999,3000,NaN,-1,undefined]; const m = analyzeCrawl(result(values.map((v,i) => page(String(i), { duration_ms: v })))); assert.deepEqual(m.timings.map(b => b.count), [2,2,2,1,3]); assert.equal(m.measured,7); assert.equal(m.median,999); assert.equal(m.p95,3000); assert.equal(percentile([], .5), null); });
test('depth totals account for every capture and disclose unknown depth', () => { const m = analyzeCrawl(result([page('a', { depth: 0 }), page('b', { title: '', depth: 2 }), page('c', { depth: undefined })])); assert.equal(m.depths.reduce((sum,d) => sum+d.clear+d.review,0), 3); assert.ok(m.depths.some(d => d.label === 'Unknown')); assert.equal(m.affected,1); });
test('filtering applies query/category/severity together without mutating source', () => { const m = analyzeCrawl(result([page('a', { title:'',description:'' }), page('b', { title:'' })])); const original = JSON.stringify(m.findings); const rows = filterFindings(m.findings, { query:'/a', category:'Content', severity:'review', order:'url' }); assert.equal(rows.length,2); assert.equal(JSON.stringify(m.findings),original); });
test('rankings cover all pages, sort unknowns last and do not mutate input', () => { const m=analyzeCrawl(result([page('a',{duration_ms:undefined}),page('b',{duration_ms:5}),page('c',{duration_ms:100})])); assert.deepEqual(rankPages(m.metrics,'duration').map(p=>p.title),['c','b','a']); assert.equal(m.metrics[0].title,'a'); });
test('preference values are strictly allowlisted with safe defaults', () => { assert.deepEqual(accessPreferences({text:'extra',contrast:true,motion:'true',tables:1,token:'private'}),{text:'extra',contrast:true,motion:false,tables:false}); assert.equal(accessPreferences({text:'999px'}).text,'normal'); assert.equal(accessPreferences(null).contrast,false); });
test('CSV export neutralizes formula-leading captured strings and quotes', () => { const text=csv([{url:'https://fixture.example',title:' =HYPERLINK("bad")',detail:'<script>not markup</script>'}]); assert.match(text,/"' =HYPERLINK\(""bad""\)"/); assert.match(text,/<script>not markup<\/script>/); });

test('redirect aliases count each source only once against the captured destination', () => { const target = page('final', { requested_url: 'https://fixture.example/old' }); const source = page('source', { internal_links: ['https://fixture.example/old#x', 'https://fixture.example/final', 'https://fixture.example/old'] }); const m = analyzeCrawl(result([target, source])); assert.equal(m.metrics.find(p => p.title === 'final').incoming, 1); });
test('invalid percentile fractions remain unknown', () => { assert.equal(percentile([10,20],NaN),null); assert.equal(percentile([10,20],Infinity),null); });
