/** Compact, truthfully labelled run telemetry and bounded active/queued URL views. */
import type { Job } from '../src/studio/jobs.js';
import { esc, bytes } from './atlas-shared.js';
export function renderTelemetry(target: HTMLElement, job: Job): void {
  const result=job.result, t=result?.telemetry, frontier=result?.discovery?.frontier??[];
  const queued=frontier.filter(f=>f.state==='queued'), processing=frontier.filter(f=>f.state==='processing');
  const elapsed=Math.max(1,(result?.duration_ms??0)/1000);
  const rows: [string,string,string][]=[['HTTP',String(t?.http_pages??job.pages),'pages'],['Chromium',String(t?.browser_pages??0),'pages'],['Pending',String(queued.length),'URLs'],['Mean rate',((result?.summary.requests??0)/elapsed).toFixed(1),'req/s'],['Received',bytes(t?.body_bytes??0),'decoded bodies'],['Node RSS',`${t?.process_rss_mb??0} MiB`,'not Chromium RSS']];
  const old=target.querySelector<HTMLDetailsElement>('details')?.open;
  target.innerHTML=`<div class="telemetry-strip">${rows.map(([name,value,unit])=>`<div><span>${name}</span><strong>${esc(value)}</strong><small>${unit}</small></div>`).join('')}<div><span>Active / limit</span><strong>${t?.http_active??0} HTTP · ${t?.browser_active??0} browser</strong><small>${t?.effective_workers??job.options.maxConcurrency} page workers · ${job.options.browserConcurrency??2} browser contexts</small></div></div><details class="control-center" ${old?'open':''}><summary>Control center · ${processing.length} processing · ${t?.browser_queued??0} awaiting Chromium ${t?.throttle_reason?'· memory throttling':''}</summary><div class="control-columns"><section><h3>Processing now</h3>${processing.slice(0,16).map(f=>`<p>${esc(f.url)}</p>`).join('')||'<p>No active page visits.</p>'}</section><section><h3>Next in frontier</h3>${queued.slice(0,12).map(f=>`<p><b>${esc(f.method)}</b> ${esc(f.url)}</p>`).join('')||'<p>No queued page URLs.</p>'}</section><section><h3>Limits &amp; decisions</h3><p>${esc(job.options.mode??'http')} mode · ${job.options.delayMs} ms request spacing</p><p>${job.options.renderTimeoutMs??15000} ms render deadline · ${job.options.scrollIterations??0} scroll iterations</p><p>${result?.summary.retries??0} HTTP retries · ${t?.browser_requests??0} browser resource attempts</p><p>${esc(t?.throttle_reason||'Configured speed is active. Browser contexts have a separate ceiling.')}</p></section></div></details>`;
}
